name: Test
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: "43 19 * * 0"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup bazel
        uses: abhinavsingh/setup-bazel@v3
        with:
          version: 4.0.0
      - name: Checkout
        uses: actions/checkout@v2
      - name: Test
        run: "bazel test //..."
